- name: add entries to /etc/hosts for all cluster members
  lineinfile:
    state: present
    dest: /etc/hosts
    line: "{{ hostvars[item]['ansible_ssh_host'] }} {{ item }} {{ item }}"
  when: "{{ hostvars[item]['ansible_ssh_host'] is defined }}"
  with_items: "{{ groups['all'] }}"

- name: open port 8081 for web UI
  lineinfile:
    line: "-A INPUT -p tcp -m tcp --dport 8081 -j ACCEPT"
    dest: /etc/sysconfig/iptables
    insertbefore: '^-A INPUT'

- name: open port for master
  lineinfile:
    line: "-A INPUT -s {{ hostvars[groups['masters'][0]]['ansible_ssh_host'] }} -j ACCEPT"
    dest: /etc/sysconfig/iptables
    insertbefore: '^-A INPUT'

- name: open ports for nodes
  lineinfile:
    line: "-A INPUT -s {{ hostvars[item]['ansible_ssh_host'] }} -j ACCEPT"
    dest: /etc/sysconfig/iptables
    insertbefore: '^-A INPUT'
  with_items: "{{ groups['nodes'] }}"

- name: restart iptables
  service: name=iptables state=restarted