- name: install basic tools
  yum: pkg={{item}} state=present
  with_items:
    - dstat
    - lsof
    - bash-completion
    - time
    - tmux
    - git
    - xauth
    - screen
    - nano
    - vim
    - bind-utils
    - nmap-ncat
    - lvm2
    - chrony
    - bzip2
    - iptables-services
    - perl-CPAN
    - perl-Digest-MD5
    - sudo
    - wget

- name: stop cloud-init managing /etc/hosts
  lineinfile:
    dest: /etc/cloud/cloud.cfg.d/10_etc_hosts.cfg
    state: present
    regexp: '^manage_etc_hosts'
    line: 'manage_etc_hosts: False'
    create: yes

- name: fix /etc/hosts after cloud-init IPv4
  lineinfile:
    dest: /etc/hosts
    state: absent
    regexp: "^127.0.0.1(.*){{ inventory_hostname }}(.*)"

- name: fix /etc/hosts after cloud-init IPv6
  lineinfile:
    dest: /etc/hosts
    state: absent
    regexp: "^::1(.*){{ inventory_hostname }}(.*)"

- name: remove ntp.org pool hosts from config
  lineinfile:
    dest: /etc/chrony.conf
    state: absent
    regexp: '^server .*ntp.org iburst'
  when: '{{ custom_ntp_servers is defined }}'
  notify: restart chronyd

- name: add custom servers to NTP config
  lineinfile:
    dest: /etc/chrony.conf
    state: present
    line: 'server {{ item }} iburst'
  with_items: '{{ custom_ntp_servers|default([]) }}'
  when: '{{ custom_ntp_servers is defined }}'
  notify: restart chronyd

- name: enabled chronyd
  service: name=chronyd enabled=yes

- name: disable firewalld
  command: "{{ item }}"
  with_items:
    - systemctl stop firewalld
    - systemctl mask firewalld

- name: enable iptables
  command: "{{ item }}"
  with_items:
    - systemctl enable iptables
    - systemctl enable ip6tables
    - systemctl start iptables
    - systemctl start ip6tables

- name: disable tty
  command: "sed -i -e 's/Defaults    requiretty.*/ #Defaults    requiretty/g' /etc/sudoers"

- name: set hostname
  hostname:
    name: "{{ inventory_hostname }}"
