---
- name: point resolv.conf to master(s)
  lineinfile:
    dest: /etc/resolv.conf
    insertafter: '^search.*'
    line: "nameserver {{ hostvars[item]['ansible_ssh_host'] }}"
  with_items: "{{ groups['masters'] }}"

- name: create dhclient.conf
  command: touch /etc/dhcp/dhclient.conf
  args:
    creates: /etc/dhcp/dhclient.conf

- name: make sure our local DNS gets inserted by dhclient too
  lineinfile:
    dest: /etc/dhcp/dhclient.conf
    line: "prepend domain-name-servers {{ hostvars[item]['ansible_ssh_host'] }};"
  with_items: "{{ groups['masters'] }}"

- name: add default iptables persistent state file
  template:
    src: etc/sysconfig/iptables.j2
    dest: /etc/sysconfig/iptables
    force: no

- name: generate ssh key for cloud-user
  user: name=cloud-user generate_ssh_key=yes ssh_key_type=rsa
  when: inventory_hostname in groups.masters

- name: download public keys from masters
  fetch: dest=/tmp/ansible/public_keys/ src=.ssh/id_rsa.pub
  when: inventory_hostname in groups.masters

- name: authorize ssh with the downloaded key
  authorized_key: user=cloud-user key="{{ lookup('file', '/tmp/ansible/public_keys/{{ item }}/.ssh/id_rsa.pub') }}"
  with_items: "{{ groups.masters }}"

- name: set SELinux state
  selinux: state="{{ selinux_state }}"
  when: selinux_state is defined



