- name: Configure common parts
  hosts:
    - masters
    - nodes
  vars:
    selinux_state: "disabled"
  become: yes
  roles:
    - base
    - cluster_common
    - lvm_storage
    - hortonworks_common

- name: Configure master
  hosts:
    - masters
  become: yes
  roles:
    - cluster_master
#    - ambari_server
    - role: nfs_server
      exports: "{{ nfs_shares|default([]) }}"

- name: Configure nodes
  hosts:
    - nodes
  become: yes
  roles:
    - role: nfs_client
      nfs_mounts: "{{ nfs_shares|default([]) }}"

#- name: Ambari agents
#  hosts:
#    - masters
#    - nodes
#  become: yes
#  roles:
#    - ambari_agents
#
#- name: Provision cluster in ambari using spark blueprint
#  hosts:
#    - localhost
#  become: no
#  vars:
#    master_private_ip: "{{ hostvars[groups['masters'][0]]['ansible_ssh_host'] }}"
#  roles:
#    - ambari_blueprints
