---
- name: Deploy base infra for HDP in cPouta
  hosts: localhost
  connection: local
  vars:
    cluster_name: "my-oso"
    ssh_key: "my_key"
    network_name: ""
    network_cidr: "192.168.1.0/24"
    bastion_secgroup: "bastion"
  tasks:
    - name: bastion security group - create
      register: sg_bastion
      os_security_group:
        name: "{{ bastion_secgroup }}"
        description: "Ansible generated security group for bastion"

    - name: master SG - create
      os_security_group:
        name: "{{ cluster_name }}-master"
        description: "Ansible generated security group for {{ cluster_name }}-master"

    - name: common SG - create
      register: sg_common
      os_security_group:
        name: "{{ cluster_name }}-common"
        description: "Ansible generated common security group for {{ cluster_name }}"

    # remote_group workaround for https://github.com/ansible/ansible-modules-core/issues/2855
    - name: common SG - open cluster internal access
      os_security_group_rule:
        security_group: "{{ cluster_name }}-common"
        remote_group: "{{ item }}"
      with_items:
        - ["{{ sg_common.secgroup.id }}", "{{ sg_bastion.secgroup.id }}" ]

    - name: provision master
      include: tasks/vm_group_provision.yml
      vars:
        security_groups: ["{{ cluster_name }}-master", "{{ cluster_name }}-common"]
      with_items:
        - "master"
      loop_control:
        loop_var: "vm_group_name"

    - name: assign selected public ip to master
      os_floating_ip:
        server: "{{ cluster_name }}-master-1"
        floating_ip_address: "{{ master.floating_ip }}"
      when: master.floating_ip is defined

    - name: auto-assign floating ip
      os_floating_ip:
        server: "{{ cluster_name }}-master-1"
        reuse: yes
      when: (master.auto_ip|default(false))|bool and master.floating_ip is not defined

    - name: provision nodes
      include: tasks/vm_group_provision.yml
      with_items: "{{ node_groups }}"
      loop_control:
        loop_var: "vm_group_name"

- name: Generate inventory and tmuxinator config
  hosts: localhost
  connection: local
  tasks:
    - name: create inventory on disk
      template:
        src: templates/hortonworks-inventory.j2
        dest: ./hortonworks-inventory
        backup: yes

    - name: create tmuxinator status session config
      include: tasks/create_tmuxinator_config.yml

- name: Print resource info
  hosts:
    - localhost
  tasks:
  - debug:
      msg: >
        Master has private IP {{ hostvars[cluster_name+'-master-1']['ansible_ssh_host'] }}.
