---
- name: add entries to /etc/hosts for all cluster members
  lineinfile:
    state: present
    dest: /etc/hosts
    line: "{{ hostvars[item]['ansible_ssh_host'] }} {{ item }} {{ item }}"
  when: "{{ hostvars[item]['ansible_ssh_host'] is defined }}"
  with_items: "{{ groups['all'] }}"
#  notify: restart_dnsmasq

- name: install pdsh
  yum: name=pdsh state=present

# http://developerblog.redhat.com/2015/11/19/dns-your-openshift-v3-cluster/
#- name: install dnsmasq
#  yum: name=dnsmasq state=present

#- name: enable and run dnsmasq service
#  service:
#    name: dnsmasq
#    enabled: yes
#    state: started

#- name: open ports 53 for DNS
#  lineinfile:
#    line: "-A INPUT -p udp -m udp --dport 53 -j ACCEPT"
#    dest: /etc/sysconfig/iptables
#    insertbefore: '^-A INPUT'

- name: open ports for nodes
  lineinfile:
    line: "-A INPUT -s {{ vars[vm_group_name].network_range|default([]) }} -j ACCEPT"
    dest: /etc/sysconfig/iptables
    insertbefore: '^-A INPUT'

- name: open port 8080 for web UI
  lineinfile:
    line: "-A INPUT -p tcp -m tcp --dport 8080 -j ACCEPT"
    dest: /etc/sysconfig/iptables
    insertbefore: '^-A INPUT'

- name: open port 4040 for Metapipe UI
  lineinfile:
    line: "-A INPUT -p tcp -m tcp --dport 4040 -j ACCEPT"
    dest: /etc/sysconfig/iptables
    insertbefore: '^-A INPUT'

- name: open port 7077 for Spark
  lineinfile:
    line: "-A INPUT -p tcp -m tcp --dport 7077 -j ACCEPT"
    dest: /etc/sysconfig/iptables
    insertbefore: '^-A INPUT'

- name: open port 6066 for REST server
  lineinfile:
    line: "-A INPUT -p tcp -m tcp --dport 6066 -j ACCEPT"
    dest: /etc/sysconfig/iptables
    insertbefore: '^-A INPUT'

- name: restart iptables
  service: name=iptables state=restarted
