- name: Add cvmfs repository
  yum:
    name: https://ecsft.cern.ch/dist/cvmfs/cvmfs-release/cvmfs-release-latest.noarch.rpm

- name: Install cvmfs
  yum: pkg={{item}} state=present
  with_items:
   - cvmfs
   - cvmfs-config-default

- name: Run base setup
  command: cvmfs_config setup

- name: Add metapipe repository
  lineinfile: 
    path: /etc/cvmfs/default.local
    line: "CVMFS_REPOSITORIES=metapipe.cesnet.cz"
    mode: 0777
    create: yes

- name: Add local squid proxy
  lineinfile: 
    path: /etc/cvmfs/default.local
    line: "CVMFS_HTTP_PROXY=\"http://{{ hostvars[groups['masters'][0]]['ansible_ssh_host'] }}:3128\""

- name: Download server public key
  command: wget http://stoor143.meta.zcu.cz/metapipe.cesnet.cz.pub -O /etc/cvmfs/keys/metapipe.cesnet.cz.pub

- name: Add repository URL
  lineinfile:
    path: /etc/cvmfs/config.d/metapipe.cesnet.cz.conf
    line: "CVMFS_SERVER_URL=http://stoor143.meta.zcu.cz/cvmfs/metapipe.cesnet.cz"
    mode: 0777
    create: yes

- name: Add public key to repository
  lineinfile:
    path: /etc/cvmfs/config.d/metapipe.cesnet.cz.conf
    line: "CVMFS_PUBLIC_KEY=/etc/cvmfs/keys/metapipe.cesnet.cz.pub"

- name: Mount repository
  command: cvmfs_config probe