- name: Install nfs utils		
  yum:
    name: nfs-utils
    state: present

- name: make sure mount path exists
  file:
    path: "{{ item.directory }}"
    state: directory
  with_items: "{{ nfs_mounts }}"

- name: mount and update fstab
  mount:
    name: "{{ item.directory }}"
    src: "{{ item.server|default(hostvars[groups['masters'][0]]['ansible_ssh_host']) }}:{{ item.directory }}"
    fstype: "nfs"
    opts: "{{ item.mount_options|default('defaults,_netdev') }}"
    state: mounted
  with_items: "{{ nfs_mounts }}"