- name: nfs client
  yum: pkg={{item}} state=present
  with_items:
    - nfs-utils

- mount: name={{item}} src={{hostvars[groups['masters'][0]]['ansible_ssh_host']}}:{{item}} fstype=nfs state=mounted
  with_items:
    #- /home
    - /data
    - /export/share

- name: open port 8081 for web UI
  lineinfile:
    line: "-A INPUT -p tcp -m tcp --dport 8081 -j ACCEPT"
    dest: /etc/sysconfig/iptables
    insertbefore: '^-A INPUT'

- name: open ports for other nodes and master
  lineinfile:
    line: "-A INPUT -s 147.228.242.0/24 -j ACCEPT"
    dest: /etc/sysconfig/iptables
    insertbefore: '^-A INPUT'

- name: restart iptables
  service: name=iptables state=restarted
