- name: open port 8081 for web UI
  lineinfile:
    line: "-A INPUT -p tcp -m tcp --dport 8081 -j ACCEPT"
    dest: /etc/sysconfig/iptables
    insertbefore: '^-A INPUT'

- name: open ports for other nodes and master
  lineinfile:
    line: "-A INPUT -s 147.228.242.0/24 -j ACCEPT"
    dest: /etc/sysconfig/iptables
    insertbefore: '^-A INPUT'

- name: restart iptables
  service: name=iptables state=restarted

- name: make sure mount path exists
  file:
    path: "{{ item.directory }}"
    state: directory
  with_items: "{{ nfs_mounts }}"

- name: mount and update fstab
  mount:
    name: "{{ item.directory }}"
    src: "{{ item.server|default(hostvars[groups['masters'][0]]['ansible_ssh_host']) }}:{{ item.directory }}"
    fstype: "nfs"
    opts: "{{ item.mount_options|default('defaults,_netdev') }}"
    state: mounted
  with_items: "{{ nfs_mounts }}"