- name: nfs-server-kernel
  yum: pkg={{item}} state=present
  with_items:
    - nfs-utils

- name: NFS Shared directory
  file: path=/var/nfs state=directory mode=0777

- name: Data directory
  file: path=/data state=directory owner=root group=root

- name: start and enable rpcbind and nfs-server
  service:
    name: "{{item}}"
    state: started
    enabled: yes
  with_items:
    - rpcbind
    - nfs-server

- name: Export Directory
  register: exports
  lineinfile: dest=/etc/exports
              regexp='^{{item}}'
              line='{{item}}  *(rw,sync,no_subtree_check,no_root_squash)'
              state=present
              create=yes
              owner=root
              group=root
  with_items:
    #- /home
    - /data
    - /export/share

- name: Create NFS table
  when: exports.changed
  command: exportfs -a

- name: NFS is restarted
  when: exports.changed
  service: name=nfs state=restarted